# Generated by Django 5.2 on 2025-04-26 22:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankaccount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BankAccount',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(max_length=20, unique=True)),
                ('transaction_type', models.CharField(choices=[('DP', 'Deposit'), ('WD', 'Withdrawal')], max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='test_bank_systems.bankaccount')),
            ],
            options={
                'db_table': 'Transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['balance'], name='BankAccount_balance_ac03a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='check_balance'),
        ),
    ]
